export enum MutationTypes {
  TOGGLE_MEAL_ID = "TOGGLE_MEAL_ID",
  ASSIGN_MEAL_ID_TO_DAY_ID = "ASSIGN_MEAL_ID_TO_DAY_ID",
  UNASSIGN_MEAL_ID = "UNASSIGN_MEAL_ID",
  ADD_SL_ITEM = "ADD_SL_ITEM",
  REMOVE_SL_ITEM = "REMOVE_SL_ITEM",
  TOGGLE_INGREDIENT_CHECK = "TOGGLE_INGREDIENT_CHECK",
  INITIALISE_STORE = "INITIALISE_STORE"
}
